language: java

jdk: # Define the execution environments
  - openjdk11

branches: # Execute job only on specific branch commits
  only:
    - main
    - development

sudo: required # Linux administrator permissions

before_install:
  - sudo apt update # Update the package list

install:
  - sudo apt install maven –y

before_script: # Run commands
  - ls -la

script: # Build the project
  - mvn clean package jacoco:report

after_success: # Notify users about the result
  - echo “Process terminated successfully”
