language: java

jdk: # Define the execution environments
  - openjdk11

sudo: required # Linux administrator permissions

before_install:
  - sudo apt update # Update the package list

before_script: # Run commands
  - ls -la

script: # Build the project
  - mvn clean install jacoco:report

after_success: # Notify users about the result
  - java -jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/test/resources/TestClass.java strcomp local output csv
  - DIFF = $(diff expected-output.csv output.csv)
  - if ["$DIFF"]
    then
      echo "Different output than expected";
      exit 1;
    fi
  - echo “Process terminated successfully”
